"""add feed_in_tariffs_json to energy_plans

Revision ID: 0b8b8209b8e5
Revises: 75b47d2eb24b
Create Date: 2026-02-15 10:31:29.171408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8b8209b8e5'
down_revision: Union[str, Sequence[str], None] = '75b47d2eb24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_in_tariffs_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_plans', schema=None) as batch_op:
        batch_op.drop_column('feed_in_tariffs_json')

    # ### end Alembic commands ###
