"""initial schema

Revision ID: 2d3817b40dcc
Revises: 
Create Date: 2026-02-14 22:36:53.958223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3817b40dcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_data_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('source_format', sa.String(length=32), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('nmi', sa.String(length=32), nullable=False),
    sa.Column('device_number', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('register_code', sa.String(length=64), nullable=True),
    sa.Column('rate_type_description', sa.String(length=64), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('interval_length_minutes', sa.Integer(), nullable=False),
    sa.Column('profile_read_value', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('register_read_value', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('quality_flag', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'nmi', 'register_code', 'start_at', name='uq_meter_interval_row')
    )
    with op.batch_alter_table('meter_data_intervals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_data_intervals_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_data_intervals_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_data_intervals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_data_intervals_nmi'), ['nmi'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_data_intervals_rate_type_description'), ['rate_type_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_data_intervals_register_code'), ['register_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_data_intervals_source_format'), ['source_format'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_data_intervals_start_at'), ['start_at'], unique=False)

    op.create_table('retailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('retailers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retailers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retailers_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('energy_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('network_provider', sa.String(length=64), nullable=True),
    sa.Column('tariff_type', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('daily_supply_charge_cents', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('usage_rate_cents_per_kwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'plan_name', 'effective_from', 'network_provider', name='uq_energy_plan_ver')
    )
    with op.batch_alter_table('energy_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_plans_retailer_id'), ['retailer_id'], unique=False)

    op.create_table('user_nmis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nmi', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('service_address', sa.String(length=512), nullable=True),
    sa.Column('suburb', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=8), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocode_source', sa.String(length=32), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'nmi', name='uq_user_nmi')
    )
    with op.batch_alter_table('user_nmis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_nmis_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nmis_nmi'), ['nmi'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nmis_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('tou_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['energy_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_key', 'name', 'effective_from', 'plan_id', name='uq_tou_definition_ver')
    )
    with op.batch_alter_table('tou_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tou_definitions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tou_definitions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tou_definitions_scope_key'), ['scope_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tou_definitions_scope_type'), ['scope_type'], unique=False)

    op.create_table('user_nmi_plan_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_nmi_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('retailer_name', sa.String(length=128), nullable=True),
    sa.Column('retail_plan_id', sa.Integer(), nullable=True),
    sa.Column('network_tariff_code', sa.String(length=64), nullable=True),
    sa.Column('source_invoice_file_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['retail_plan_id'], ['energy_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_nmi_id'], ['user_nmis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_nmi_plan_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_nmi_plan_assignments_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nmi_plan_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nmi_plan_assignments_source_invoice_file_id'), ['source_invoice_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nmi_plan_assignments_user_nmi_id'), ['user_nmi_id'], unique=False)

    op.create_table('tou_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.String(length=64), nullable=False),
    sa.Column('rate_cents_per_kwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('demand_rate_cents_per_kva', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['tou_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tou_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tou_periods_definition_id'), ['definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tou_periods_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tou_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tou_periods_id'))
        batch_op.drop_index(batch_op.f('ix_tou_periods_definition_id'))

    op.drop_table('tou_periods')
    with op.batch_alter_table('user_nmi_plan_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nmi_plan_assignments_user_nmi_id'))
        batch_op.drop_index(batch_op.f('ix_user_nmi_plan_assignments_source_invoice_file_id'))
        batch_op.drop_index(batch_op.f('ix_user_nmi_plan_assignments_id'))
        batch_op.drop_index(batch_op.f('ix_user_nmi_plan_assignments_effective_from'))

    op.drop_table('user_nmi_plan_assignments')
    with op.batch_alter_table('tou_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tou_definitions_scope_type'))
        batch_op.drop_index(batch_op.f('ix_tou_definitions_scope_key'))
        batch_op.drop_index(batch_op.f('ix_tou_definitions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_tou_definitions_id'))

    op.drop_table('tou_definitions')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_nmis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nmis_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_nmis_nmi'))
        batch_op.drop_index(batch_op.f('ix_user_nmis_id'))

    op.drop_table('user_nmis')
    with op.batch_alter_table('energy_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_plans_retailer_id'))
        batch_op.drop_index(batch_op.f('ix_energy_plans_id'))

    op.drop_table('energy_plans')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_account_type'))

    op.drop_table('users')
    with op.batch_alter_table('retailers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retailers_slug'))
        batch_op.drop_index(batch_op.f('ix_retailers_id'))

    op.drop_table('retailers')
    with op.batch_alter_table('meter_data_intervals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_data_intervals_start_at'))
        batch_op.drop_index(batch_op.f('ix_meter_data_intervals_source_format'))
        batch_op.drop_index(batch_op.f('ix_meter_data_intervals_register_code'))
        batch_op.drop_index(batch_op.f('ix_meter_data_intervals_rate_type_description'))
        batch_op.drop_index(batch_op.f('ix_meter_data_intervals_nmi'))
        batch_op.drop_index(batch_op.f('ix_meter_data_intervals_id'))
        batch_op.drop_index(batch_op.f('ix_meter_data_intervals_file_id'))
        batch_op.drop_index(batch_op.f('ix_meter_data_intervals_account_number'))

    op.drop_table('meter_data_intervals')
    # ### end Alembic commands ###
