"""add feed_in_tariff_cents_per_kwh to energy_plans

Revision ID: 75b47d2eb24b
Revises: 2d3817b40dcc
Create Date: 2026-02-15 01:30:20.355152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b47d2eb24b'
down_revision: Union[str, Sequence[str], None] = '2d3817b40dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_in_tariff_cents_per_kwh', sa.Numeric(precision=12, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_plans', schema=None) as batch_op:
        batch_op.drop_column('feed_in_tariff_cents_per_kwh')

    # ### end Alembic commands ###
